baseURL = "https://www.dave4everkw.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/blog"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
