baseURL = "https://dave-julien.netlify.app/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Resources"
weight = 3
[[menu.main]]
name = "Buyers"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/blog"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
